# K8s Deployments (No persistent IDs/storage) for the Stateless producer & consumer. Resilience and scalability as they interchangeable. 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pets-producer
spec:
  replicas: 1
  selector: # Identifying pods
    matchLabels:
      app: pets-producer
  template: # For creating pods
    metadata:
      labels:
        app: pets-producer
    spec:
      containers:
      - name: producer
        image: localhost:5000/god_bless-producer:v11
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKERS
          value: "kafka-0.kafka.default.svc.cluster.local:9092"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pets-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pets-consumer
  template:
    metadata:
      labels:
        app: pets-consumer
    spec:
      containers:
      - name: consumer
        image: localhost:5000/god_bless-consumer:latest
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKERS
          value: "kafka-0.kafka.default.svc.cluster.local:9092"
