apiVersion: apps/v1
kind: Deployment
metadata:
  name: pets-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pets-producer
  template:
    metadata:
      labels:
        app: pets-producer
    spec:
      containers:
      - name: producer
        image: localhost:5000/god_bless-producer:latest
        env:
        - name: KAFKA_BROKERS
          value: "kafka-0.kafka.default.svc.cluster.local:9092,kafka-1.kafka.default.svc.cluster.local:9092,kafka-2.kafka.default.svc.cluster.local:9092"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pets-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pets-consumer
  template:
    metadata:
      labels:
        app: pets-consumer
    spec:
      containers:
      - name: consumer
        image: localhost:5000/god_bless-consumer:latest
        env:
        - name: KAFKA_BROKERS
          value: "kafka-0.kafka.default.svc.cluster.local:9092,kafka-1.kafka.default.svc.cluster.local:9092,kafka-2.kafka.default.svc.cluster.local:9092"
