# K8s Services for Kafka and ZooKeeper, enabling network access for Kafka brokers and ZooKeeper nodes 

# Kafka headless service for the clients to connect my Kafka brokers
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
  - port: 9092

---
# Zookeeper ClusterIP service for the client (Kafka) to connect ZooKeeper ensemble (receptionist)
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - port: 2181